### ISSUE TITLE
20160107 LCD操作中，黑白屏像素格式问题

### ISSUE THREAD

**Issue by ntzyz** [haruue/NdlessNote#1]
ndless 下黑白屏的灰度模式是单个字节表示两个像素，即4位表示一个像素，`0x0`表示黑色，`0xF`表示白色，中间渐变，与彩屏机器不一样。

**Comment by haruue** [comment]
嗯，谢谢提示，Jack(六合宅客锟斤拷) 那时候分析了一下代码，结论是：对于黑白屏，是一个 Byte 对应两个像素， `[px1][px2]` 。是这样么？我将会改正一下。

**Comment by haruue** [comment]
LCD 操作写的挺乱的，那时候看不太懂二进制操作，之前还以为彩色可以直接填充黑白机。后来 Jack(六合宅客锟斤拷) 在三方群里说了下为什么这么做。不久之后将会修改内容。

**Comment by ntzyz** [comment]
应该是的，好久不接触计算器了。其实论坛里那个我写的比你还乱（捂脸

**Comment by haruue** [comment]
已经改正了这个问题于
6a7cb7f916bc95d2f8947887beacb8a43e2626ff

**Comment by ntzyz** [comment]
嗯嗯，写得很好，继续努力！
